export const unsplashPhotoAT = {
  GET_PHOTOS: 'GET_PHOTOS',
  ADD_PHOTOS: 'ADD_PHOTOS',
  GET_RANDOM_PHOTO: 'GET_RANDOM_PHOTO',
};

export const authAT = {
  SET_AUTH_INFO: 'SET_AUTH_INFO',
  SET_CURRENT_USER_INFO: 'SET_CURRENT_USER_INFO',
}

export const photoAndUserDetailsAT = {
  SET_USER_INFO: 'SET_USER_INFO',
  SET_PHOTO_INFO: 'SET_PHOTO_INFO',
}